services:
  meurs:
    image: meurs:latest            # using the locally built image
    # build: .                     # uncomment if you want compose to build it
    container_name: meurs
    ports:
      - "8000:8000"

    # load all vars from .env (must be next to this file)
    env_file:
      - .env

    # explicitly pass the ones your app reads
    environment:
      YT_API_KEY: ${YT_API_KEY:-}
      PIXABAY_KEY: ${PIXABAY_KEY:-}
      PEXELS_KEY: ${PEXELS_KEY:-}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      DB_DIR: /data                   # if your app uses this

    volumes:
      - media_data:/app/media
      - db_data:/data

    restart: unless-stopped

volumes:
  media_data:
  db_data:
