services:
  meurs:
    image: meurs:latest          # <-- use the prebuilt image
    # build: .                   # <-- REMOVE this line if present
    container_name: meurs
    ports:
      - "8000:8000"
    environment:
      - YT_API_KEY=${YT_API_KEY}
      - DB_DIR=/data             # only if you added this in database.py
    volumes:
      - media_data:/app/media
      - db_data:/data
    restart: unless-stopped

volumes:
  media_data:
  db_data:
